[package]
name = "pmemlog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
builtin_macros = { git = "https://github.com/verus-lang/verus.git", rev="309a0eca409eeec23d3f7142ca27fb3151c79025" }
builtin = { git = "https://github.com/verus-lang/verus.git", rev="309a0eca409eeec23d3f7142ca27fb3151c79025" }
vstd = { git = "https://github.com/verus-lang/verus.git", rev="309a0eca409eeec23d3f7142ca27fb3151c79025" }
crc64fast = "1.0.0"
