[package]
name = "multilog"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
builtin_macros = { git = "https://github.com/verus-lang/verus.git", rev="0bfb56eb67d0de7ab71ae316466faf302b321db3" }
builtin = { git = "https://github.com/verus-lang/verus.git", rev="0bfb56eb67d0de7ab71ae316466faf302b321db3" }
vstd = { git = "https://github.com/verus-lang/verus.git", rev="0bfb56eb67d0de7ab71ae316466faf302b321db3" }
crc = "3.0"
rand = "0.8.5"
crc64fast = "1.0.0"

[package.metadata.verus.ide]
extra_args = "--expand-errors"
